version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://kalibran_user:kalibran_password@db:5432/kalibran_db
      - JWT_SECRET=your_super_secret_jwt_key # Users should change this
      # External DB credentials will be stored in the database after setup

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=kalibran_user
      - POSTGRES_PASSWORD=kalibran_password
      - POSTGRES_DB=kalibran_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kalibran_user -d kalibran_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
